#!/usr/bin/env python3
import sys

from run import run

from lib.parse    import parse
from lib.generate import generate, generate_program

'''
This script compiles and runs a .lisp (curry) file.
Its usage is ./compile [filename]
An auxilary quil file will be output to '.out.quil'
'''

def main(args):
    assert len(args) > 0, 'Usage: ./compile [filename]'
    filename = args[0]
    with open(filename, 'r') as infile:
        body = infile.read()
    stack = parse(body)
    program = generate_program(stack)
    print(program)
    1/0

    quil  = generate(stack)
    quilfile = '.out.quil'
    with open(quilfile, 'w') as outfile:
        outfile.write(quil)
    run(quilfile)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
