#!/usr/bin/env python3
import sys

from pyquil import get_qc

from curry.parse    import parse
from curry.generate import generate, generate_program

from pprint import pprint

'''
This script compiles and runs a .lisp (curry) file.
Its usage is ./compile [filename]
An auxilary quil file will be output to '.out.quil'
'''

def main(args):
    assert len(args) > 0, 'Usage: ./compile [filename]'
    filename = args[0]
    with open(filename, 'r') as infile:
        body = infile.read()
    stack = parse(body)
    program = generate_program(stack)
    print('Program:')
    print(program)
    print('End')
    qc = get_qc('9q-square-qvm')
    result = qc.run_and_measure(program, trials=10)
    pprint(result)

    quil = str(program)
    quilfile = '.out.quil'
    with open(quilfile, 'w') as outfile:
        outfile.write(quil)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
