#!/usr/bin/env python3
import sys

from pyquil.quil import Program
from pyquil.api import QVMConnection
from pyquil.gates import CNOT, H

def main(args):
    assert len(args) > 0, 'Usage: ./exec_file [filename]'
    filename = args[0]
    qvm = QVMConnection()
    with open(filename, 'r') as infile:
        program = Program(infile.read())
    wave_function = qvm.wavefunction(program)
    print(wave_function)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
