#!/usr/bin/env python3
from pyquil.gates import STANDARD_INSTRUCTIONS
import pyquil.gates

from pprint import pprint

import inspect

for k, v in STANDARD_INSTRUCTIONS.items():
    if callable(v):
        aspec = inspect.getfullargspec(v)
        print(k)
        print('    ' + str(aspec.args))
