#!/usr/bin/env python3
import sys

from lib.gaussian import Gaussian

def main(args):
    g = Gaussian(1.0, 1.0, 5)
    print(g.gaussian_wavefunc().pretty_print_probabilities())
    print(g.prog._out(True))

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
